### ISSUE TITLE
How to install unrar on Windows?

### ISSUE THREAD

**Issue by adamjstewart** [markokr/rarfile#72]
Disclaimer: I'm not a Windows person

I'm using `rarfile` in my project and using GitHub Actions to run tests on Linux/macOS/Windows. `pip` installs `rarfile` just fine, but I need an `unrar` command to actually use it. I've figured out how to do this for Linux/macOS using:
```yaml
    - name: Install apt dependencies
      run: sudo apt-get install unrar
      if: ${{ runner.os == 'Linux' }}
    - name: Install brew dependencies
      run: brew install rar
      if: ${{ runner.os == 'macOS' }}
```
but I haven't yet figured out how to install `unrar` from the command line on Windows. Another option would be for `conda` to install both `rarfile` and `unrar`. I opened an issue for this at https://github.com/conda-forge/rarfile-feedstock/issues/4.
